# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: git+https://github.com/OCA/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 16.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: "Management Information System reports for Odoo: easily build super\
    \ fast,\nbeautiful, custom reports such as P&L, Balance Sheets and more.\n\nThis\
    \ project implements a class of reports where KPI (Key Performance Indicators)\n\
    are displayed in rows, and time periods in columns. It focuses on very fast reporting\n\
    on accounting data but can also use data from any other Odoo model.\n\nIt features\
    \ the following key characteristics:\n\n- User configurable: end users can create\
    \ new report templates without development,\n  using simple Excel-like formulas.\n\
    - Very fast balance reporting for accounting data, even on million lines databases\n\
    \  and very complex account charts.\n- Use the same template for different reports.\n\
    - Compare data over different time periods.\n- User-configurable styles, rendered\
    \ perfectly in the UI as well as Excel and PDF exports.\n- Interactive display\
    \ with drill-down.\n- Export to PDF and Excel.\n- A budgeting module.\n- Evaluate\
    \ KPI over various data sources, such as actuals, simulation, committed costs\n\
    \  (some custom development is required to create the data source).\n- For developers,\
    \ the accounting balance computation engine is exposed as an easy\n  to use API.\n\
    \nHere are some presentations:\n\n- Odoo Experience 2017 ([slides](https://www.slideshare.net/acsone/budget-control-with-misbuilder-3-2017),\
    \ [video](https://youtu.be/0PpxGAf2l-0))\n- Odoo Experience 2016 ([slides](https://www.slideshare.net/acsone/misbuilder-2016))\n\
    - Odoo Experience 2015 ([slides](https://www.slideshare.net/acsone/misbuilder))"
repo_name: MIS Builder
repo_slug: mis-builder
repo_website: https://github.com/OCA/mis-builder
travis_apt_packages: []
travis_apt_sources: []

