# Do NOT update manually; changes here will be overwritten by Copier
_commit: v3.0.7
_src_path: https://github.com/grap/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: null
repo_name: MIS Builder
repo_slug: mis-builder
repo_website: https://github.com/OCA/mis-builder
travis_apt_packages: []
travis_apt_sources: []

